# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-17 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='cell_phone',
            field=models.CharField(default='123 456 7890', max_length=120),
        ),
        migrations.AddField(
            model_name='address',
            name='home_phone',
            field=models.CharField(default='123 456 7890', max_length=120),
        ),
    ]
