# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-20 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20180317_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line_2',
            field=models.CharField(default='', max_length=120),
        ),
    ]
