# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-16 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daycare',
            name='typeOfPeople',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('MANAGER', 'manager'), ('EMPLOYEE', 'employee'), ('PARENT', 'parent')], default='parent', max_length=1),
            preserve_default=False,
        ),
    ]
