# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-16 04:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daycares', '0002_daycare_typeofpeople'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daycare',
            name='typeOfPeople',
        ),
    ]
