# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-05 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycares', '0003_remove_daycare_typeofpeople'),
    ]

    operations = [
        migrations.AddField(
            model_name='daycare',
            name='CSST',
            field=models.DecimalField(decimal_places=6, default=0.68, max_digits=10),
        ),
    ]
