# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-14 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycares', '0004_daycare_csst'),
    ]

    operations = [
        migrations.AddField(
            model_name='daycare',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
