# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-14 00:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daycares', '0005_daycare_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daycare',
            name='balance',
        ),
    ]
