# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-19 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycares', '0007_daycare_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='daycare',
            name='NEQ',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='daycare',
            name='account_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='daycare',
            name='identification_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
