# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-19 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daycares', '0008_auto_20180519_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daycare',
            old_name='data',
            new_name='unique_taxes',
        ),
    ]
