# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-20 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycares', '0009_auto_20180519_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daycare',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
