# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-14 00:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daycares', '0006_remove_daycare_balance'),
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='daycare',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='daycares.Daycare'),
            preserve_default=False,
        ),
    ]
