# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-28 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_bank_daycare'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='amount',
            new_name='checking_amount',
        ),
        migrations.AddField(
            model_name='bank',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
