# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-28 00:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20180528_0019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='checking_amount',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='credit_amount',
        ),
    ]
