# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-19 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QPIP_Employee', models.DecimalField(decimal_places=6, default=0.00548, max_digits=10)),
                ('QPIP_Employer', models.DecimalField(decimal_places=6, default=0.00767, max_digits=10)),
                ('QPP_Employee', models.DecimalField(decimal_places=6, default=0.04564, max_digits=10)),
                ('QPP_Employer', models.DecimalField(decimal_places=6, default=0.04564, max_digits=10)),
                ('EI_Employee', models.DecimalField(decimal_places=6, default=0.013, max_digits=10)),
                ('EI_Employer', models.DecimalField(decimal_places=6, default=0.0182, max_digits=10)),
                ('Federal_Income_Tax', models.DecimalField(decimal_places=6, default=0.04522, max_digits=10)),
                ('Quebec_Income_Tax', models.DecimalField(decimal_places=6, default=0.04283, max_digits=10)),
                ('CSST', models.DecimalField(decimal_places=6, default=0.68, max_digits=10)),
                ('QHSF_Employer', models.DecimalField(decimal_places=6, default=0.023, max_digits=10)),
                ('CNT_Employer', models.DecimalField(decimal_places=6, default=0.0007, max_digits=10)),
                ('Vacation_Pay', models.DecimalField(decimal_places=6, default=0.04, max_digits=10)),
            ],
        ),
    ]
