# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-19 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Taxes',
            new_name='Tax',
        ),
    ]
