# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-05 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0002_auto_20180319_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tax',
            name='CSST',
        ),
    ]
