# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-19 17:28
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0004_tax_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='data',
            field=jsonfield.fields.JSONField(default={b'CNT_Employer': 0.0007, b'EI_Employee': 0.013, b'EI_Employer': 0.0182, b'Federal_Income_Tax': 0.04522, b'QHSF_Employer': 0.023, b'QPIP_Employee': 0.00548, b'QPIP_Employer': 0.00767, b'QPP_Employee': 0.04564, b'QPP_Employer': 0.04564, b'Quebec_Income_Tax': 0.04283, b'Vacation_Pay': 0.04}),
        ),
    ]
