# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-15 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180315_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parents',
            field=models.BooleanField(default=False),
        ),
    ]
