# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-17 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='manager',
            field=models.BooleanField(default=False),
        ),
    ]
