# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-17 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycares', '0003_remove_daycare_typeofpeople'),
        ('accounts', '0004_user_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='daycare',
        ),
        migrations.AddField(
            model_name='user',
            name='daycare',
            field=models.ManyToManyField(blank=True, null=True, to='daycares.Daycare'),
        ),
    ]
