# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-17 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180317_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='daycare',
            field=models.ManyToManyField(to='daycares.Daycare'),
        ),
    ]
