# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-18 06:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180317_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='parents',
            new_name='parent',
        ),
    ]
