# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-22 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_auto_20180322_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='year',
            field=models.DateTimeField(null=True),
        ),
    ]
