# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-22 06:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_payroll_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='year',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 22, 6, 10, 7, 730016, tzinfo=utc)),
        ),
    ]
