# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-13 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import payroll.models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_payroll_amount_cheque'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='proof_payed',
            field=models.FileField(blank=True, null=True, upload_to=payroll.models.upload_image_path),
        ),
    ]
