# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-13 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_payroll_proof_payed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='proof_payed',
            new_name='proof_of_payement',
        ),
    ]
