# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-20 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_auto_20180513_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
