# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 19:31
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_payroll_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='taxes',
            field=jsonfield.fields.JSONField(blank=True, default={}, null=True),
        ),
    ]
