# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 18:17
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0013_auto_20180521_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='payroll_taxes',
            new_name='company_taxes',
        ),
        migrations.AddField(
            model_name='payroll',
            name='employee_taxes',
            field=jsonfield.fields.JSONField(blank=True, default={}, null=True),
        ),
    ]
