# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0014_auto_20180526_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='CNT_Employer',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='CNT_Employer_YTD',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='CSST',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='CSST_YTD',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='EI_Employee',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='EI_Employee_YTD',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='EI_Employer',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='EI_Employer_YTD',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='Federal_Income_Tax',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='Federal_Income_Tax_YTD',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='QHSF_Employer',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='QHSF_Employer_YTD',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='QPIP_Employee',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='QPIP_Employee_YTD',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='QPIP_Employer',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='QPIP_Employer_YTD',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='QPP_Employee',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='QPP_Employee_YTD',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='QPP_Employer',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='QPP_Employer_YTD',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='Quebec_Income_Tax',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='Quebec_Income_Tax_YTD',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='Vacation_Pay',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='Vacation_Pay_YTD',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='amount_YTD',
        ),
    ]
