# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-18 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kid',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='kid',
            name='last_name',
            field=models.CharField(default='Doe', max_length=120),
            preserve_default=False,
        ),
    ]
