# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-18 05:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0002_auto_20180318_0523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kid',
            old_name='first_name',
            new_name='child_first_name',
        ),
        migrations.RenameField(
            model_name='kid',
            old_name='last_name',
            new_name='child_last_name',
        ),
    ]
